# Generated by Django 5.0.6 on 2024-07-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FansDeGreciaAntigua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=250)),
                ('mayorDeEdad', models.BooleanField()),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.fansdegreciaantigua')),
            ],
        ),
    ]
