# Generated by Django 5.0.6 on 2024-07-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiles',
            old_name='fan',
            new_name='mote',
        ),
    ]
